site_name: Template Bot Project - Python
repo_url: https://github.com/botcity-dev/bot-python-template
repo_name: ""
copyright: BotCity &copy; - All rights reserved

nav:
    - Home: index.md
    - Creating a Bot: creating.md
    - Exploring the Project: project.md
    - Building the Package: building.md
    - Running your Code: running.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/botcity-dev/bot-python-template
      name: BotCity Maestro SDK - Python -> GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/botcitydev
      name: BotCity on Twitter

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        watch:
          - botcity/maestro
        handlers:
          python:
            selection:
              inherited_members: false
              filters:
                - "!^_"  # exclude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
                - "!([a-z])*([A-Z])" # exclude camelCase elements
            rendering:
              show_source: false
              show_root_heading: true
